### ISSUE TITLE
Add Policy-based access control component

### ISSUE THREAD

**Issue by herzogrh** [citysciencelab/urban-model-platform#16]
There should be a component that handles access of users to model servers and to jobs based on several policies (policy enforcement point). Policies should be preferrably integrated using [open policy agent](https://www.openpolicyagent.org/)) 

For that, it is necessary that jobs are linked to users.

**Comment by herzogrh** [comment]
Policies could be for example which user (groups) have access to which processes and which jobs. Such as 
- Users from Organization B have access to Process X, Y and Z. 
- User A from Organization B has additional access to Process Q. 
- All users of Organization C have access to the jobs of Organization A
- Non-authenticated/anonymous users have access to Process X and Jobs of Organization A
etc. 

The general idea is to separate Authentication (Keycloak) and Authorization (Open Policy Agent) so that the authorization policies are not necessarily and new policies can be introduced much more easily. About the Flask package, that indeed seems outdated... I only found a [Docker Image ](https://hub.docker.com/r/openpolicyagent/opa )which has a [REST API ](https://www.openpolicyagent.org/docs/latest/rest-api/) for policy enforcement

**Comment by hwbllmnn** [comment]
We now discussed a different idea:

* the names of the model servers in the `providers.yaml` should be created as (client) roles in keycloak
* the keys of the processes in the `providers.yaml` should be created as (client) roles in keycloak

This way, users can be assigned to all processes within a model server or to some processes only. The UMP should then check if users are assigned the role for a model server or a process and deliver only the processes the user is allowed to.
