### ISSUE TITLE
_wait_for_results background job should have a delay

### ISSUE THREAD

**Issue by StefanSchuhart** [citysciencelab/urban-model-platform#9]
_wait_for_results() runs in the background and queries (GET) each servers job for the current status in a while loop until the job is finished. There should be a (configurable) delay for the loop to prevent it from making GET requests too often.

https://github.com/citysciencelab/urban-model-platform/blob/3be974092bd8d4affa593b2bac5c8a4d81ae700e/api/src/process.py#L176

**Comment by herzogrh** [comment]
Functionality added in #13
